import 'bootstrap/dist/css/bootstrap.min.css'
import type { Metadata } from "next"
import { Geist, Geist_Mono, Libre_Baskerville, Roboto } from "next/font/google"
import CustomCursor from './components/CustomCursor/CustomCursor'
import { DeviceProvider } from "./context/DeviceProvider"
import { ScrollProvider } from './context/ScrollProvider'
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
})

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Vault",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          roboto.variable,
          libreBaskerville.variable,
        ].join(" ")}
      >
        <DeviceProvider>
          <ScrollProvider>
            <CustomCursor />
            {children}
          </ScrollProvider>
        </DeviceProvider>
      </body>
    </html>
  )
}
